import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:fly_narwhal/core/network/quark_cdn_proxy/cdn_http_range_source.dart';
import 'package:fly_narwhal/core/network/quark_cdn_proxy/cdn_proxy_service.dart';

import 'support/cdn_proxy_http_fixture.dart';

/// Pure Dart HTTP checks. --slow additionally measures aggregate 1/2 MiB/s.
/// These generated bytes verify transport behavior, not native video playback.
Future<void> main(List<String> arguments) async {
  if (arguments.any((argument) => argument != '--slow')) {
    throw ArgumentError('Usage: dart run tool/cdn_proxy_check.dart [--slow]');
  }
  await _run('streaming_range');
  await _run('body_disconnect', disconnect: true);
  await _run('request_deadline', stall: true);
  if (arguments.contains('--slow')) {
    for (final rate in [1, 2]) {
      await _run('slow_$rate', rate: rate * fixtureMiB);
    }
  }
  stdout.writeln(jsonEncode({'passed': true, 'nativePlaybackVerified': false}));
}

Future<void> _run(String name,
    {int? rate, bool disconnect = false, bool stall = false}) async {
  final length = (rate == null ? 23 : 30) * fixtureMiB;
  final firstRead = Completer<void>();
  final origin = await CdnHttpFixture.start(
    length: length,
    bytesPerSecond: rate,
    disconnectAfter: disconnect ? 64 * 1024 : null,
    stallAfter: stall ? 64 * 1024 : null,
    handle: (request, entry) async {
      // The quick streaming check holds EOF until the downstream sees a prefix.
      if (rate == null &&
          !disconnect &&
          !stall &&
          entry.length > 1 &&
          entry.start == 0) {
        await entry.write(request.response, 64 * 1024);
        await firstRead.future;
      }
      return false;
    },
  );
  final source = CdnHttpRangeSource(
      requestTimeout:
          stall ? const Duration(seconds: 1) : const Duration(hours: 48));
  final failures = <Object>[];
  final service = CdnProxyService(source: source, onError: failures.add);
  final client = HttpClient()..findProxy = (_) => 'DIRECT';
  try {
    await (() async {
      final uri = await service.open(uri: origin.uri, headers: const {});
      final started = origin.clock.elapsed;
      final request = await client.getUrl(uri);
      request.headers.set(HttpHeaders.rangeHeader, 'bytes=0-');
      final response = await request.close();
      final headersAt = origin.clock.elapsed;
      _require(
          response.statusCode == HttpStatus.partialContent &&
              response.contentLength == length &&
              response.headers.value(HttpHeaders.contentRangeHeader) ==
                  'bytes 0-${length - 1}/$length',
          'Invalid downstream range headers');
      var received = 0;
      Duration? firstBodyAt;
      await for (final bytes in response) {
        firstBodyAt ??= origin.clock.elapsed;
        if (!firstRead.isCompleted) firstRead.complete();
        for (var i = 0; i < bytes.length; i++) {
          _require(bytes[i] == fixtureByteAt(received + i),
              'Corrupt or unordered body');
        }
        received += bytes.length;
      }
      final attempts =
          origin.requests.where((entry) => entry.length > 1).toList();
      final upstreamBytes =
          attempts.fold<int>(0, (sum, entry) => sum + entry.sentBytes);
      _require(received == length && upstreamBytes == length,
          'Missing or duplicated payload bytes');
      final first = attempts.first;
      final completed = attempts
          .where((entry) => entry.end == first.end && entry.completedAt != null)
          .first
          .completedAt!;
      _require(firstBodyAt != null && firstBodyAt < completed,
          'First body waited for a complete chunk');
      if (disconnect || stall) {
        _require(
            attempts.length == 4 &&
                first.sentBytes == 64 * 1024 &&
                first.end == 5 * fixtureMiB - 1 &&
                attempts.where((entry) => entry.start == 0).length == 1 &&
                attempts.any((entry) =>
                    entry.start == 64 * 1024 && entry.end == first.end),
            'Retry did not request exactly the missing suffix');
      } else {
        _require(attempts.length == 3, 'A healthy range unexpectedly retried');
      }
      await service.close().timeout(const Duration(seconds: 5));
      final released = {
        'chunks': service.allocatedChunkCount,
        'writers': service.activeWriterCount,
        'downloads': service.activeDownloadCount,
        'attempts': source.activeAttemptCount,
        'allocatedBytes': service.allocatedBufferBytes,
        'bufferedBytes': service.bufferedBytes,
      };
      _require(released.values.every((count) => count == 0) && failures.isEmpty,
          'Close left live resources or reported a terminal failure');
      stdout.writeln(jsonEncode({
        'scenario': name,
        'bytesPerSecond': rate,
        'headersMs': (headersAt - started).inMilliseconds,
        'firstBodyMs': (firstBodyAt! - started).inMilliseconds,
        'firstChunkCompletedMs': (completed - started).inMilliseconds,
        'firstBodyBeforeFirstChunkCompleted': true,
        'requestRanges': attempts.map((entry) => entry.toJson()).toList(),
        'retries': attempts.length - 3,
        'receivedBytes': received,
        'upstreamBytes': upstreamBytes,
        'peakRequests': origin.peakActiveRequests,
        'peakChunks': service.peakAllocatedChunkCount,
        'afterClose': released,
      }));
    })()
        .timeout(const Duration(seconds: 90));
  } finally {
    if (!firstRead.isCompleted) firstRead.complete();
    client.close(force: true);
    await service.close().timeout(const Duration(seconds: 5));
    await origin.close();
  }
}

void _require(bool condition, String message) {
  if (!condition) throw StateError(message);
}
