if(NOT DEFINED GO_EXECUTABLE OR GO_EXECUTABLE STREQUAL "")
  message(FATAL_ERROR "GO_EXECUTABLE is required")
endif()
if(NOT DEFINED UPDATER_SOURCE_DIR OR UPDATER_SOURCE_DIR STREQUAL "")
  message(FATAL_ERROR "UPDATER_SOURCE_DIR is required")
endif()
if(NOT DEFINED UPDATER_OUTPUT OR UPDATER_OUTPUT STREQUAL "")
  message(FATAL_ERROR "UPDATER_OUTPUT is required")
endif()
if(NOT DEFINED UPDATER_OUTPUT_TMP OR UPDATER_OUTPUT_TMP STREQUAL "")
  message(FATAL_ERROR "UPDATER_OUTPUT_TMP is required")
endif()
if(NOT DEFINED UPDATER_GOARCH OR UPDATER_GOARCH STREQUAL "")
  message(FATAL_ERROR "UPDATER_GOARCH is required")
endif()
if(NOT DEFINED UPDATER_CONFIGURATION OR UPDATER_CONFIGURATION STREQUAL "")
  message(FATAL_ERROR "UPDATER_CONFIGURATION is required")
endif()

get_filename_component(UPDATER_OUTPUT_DIR "${UPDATER_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${UPDATER_OUTPUT_DIR}")
file(REMOVE "${UPDATER_OUTPUT}" "${UPDATER_OUTPUT_TMP}")

execute_process(
  COMMAND "${GO_EXECUTABLE}" version
  RESULT_VARIABLE GO_VERSION_RESULT
  OUTPUT_VARIABLE GO_VERSION_OUTPUT
  ERROR_VARIABLE GO_VERSION_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE
)
if(NOT GO_VERSION_RESULT EQUAL 0)
  message(FATAL_ERROR "Failed to execute 'go version': ${GO_VERSION_ERROR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env
    "CGO_ENABLED=0"
    "GOOS=windows"
    "GOARCH=${UPDATER_GOARCH}"
    "${GO_EXECUTABLE}"
    "build"
    "-trimpath"
    "-ldflags"
    "-s -w"
    "-o"
    "${UPDATER_OUTPUT_TMP}"
    "./cmd/updater"
  WORKING_DIRECTORY "${UPDATER_SOURCE_DIR}"
  RESULT_VARIABLE GO_BUILD_RESULT
  OUTPUT_VARIABLE GO_BUILD_OUTPUT
  ERROR_VARIABLE GO_BUILD_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE
)
if(NOT GO_BUILD_RESULT EQUAL 0)
  message(FATAL_ERROR "go build failed for updater: ${GO_BUILD_ERROR}${GO_BUILD_OUTPUT}")
endif()

if(NOT EXISTS "${UPDATER_OUTPUT_TMP}")
  message(FATAL_ERROR "Updater temporary output is missing: ${UPDATER_OUTPUT_TMP}")
endif()

file(SIZE "${UPDATER_OUTPUT_TMP}" UPDATER_SIZE)
if(UPDATER_SIZE EQUAL 0)
  message(FATAL_ERROR "Updater temporary output is empty: ${UPDATER_OUTPUT_TMP}")
endif()

file(RENAME "${UPDATER_OUTPUT_TMP}" "${UPDATER_OUTPUT}")
file(SHA256 "${UPDATER_OUTPUT}" UPDATER_SHA256)
message(STATUS
  "Built updater.exe config=${UPDATER_CONFIGURATION} "
  "go_version=${GO_VERSION_OUTPUT} goarch=${UPDATER_GOARCH} "
  "size=${UPDATER_SIZE} sha256=${UPDATER_SHA256}"
)
